version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: filesharing
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  backend:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - uploaded_files:/app/uploaded_files
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  db_data:
  uploaded_files: 